
name : Experiment

on :
  push :
    branches : [ master ]
  pull_request :
    branches : [ master ]
  pull_request_review :
    branches : [ master ]

jobs :

  Fast :
    if : "!startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast  : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
        node-version : [ 14.x ]
    steps :
    - uses : actions/checkout@v2
    - run : git config --global user.email "testing@testing.com"
    - run : git config --global user.name "Testing"
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm i
    - run : node proto/dwtools/abase/l4.test/ProcessBasic.test.s r:shellArgumentsNestedQuotes v:10
    - run : node proto/dwtools/abase/l4.test/ProcessBasic.test.s r:shellModeShellNonTrivial v:10